version: '3.1'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickpass123
    volumes:
      - clickhouse-data:/var/lib/clickhouse
volumes:
  clickhouse-data: